#region License

//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

using System.Collections.Generic;

using Endjin.Templify.Domain.Domain.Packager.Tokeniser;
using Endjin.Templify.Specifications;

using Machine.Specifications;

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

#endregion

namespace Endjin.Templify.Specifications
{
    #region Using Directives

    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;

    using Endjin.Templify.Domain.Domain.Packager.Specifications;

    using Machine.Specifications;
    using Machine.Specifications.AutoMocking.Rhino;

    #endregion

    public abstract class specification_for_file_exclusion_specification
    {
        protected static List<string> file_list;

        private Establish context = () =>
            {
                file_list = new List<string>
                    {
                        @"C:\__NAME__\.git\hooks\applypatch-msg.sample",
                        @"C:\__NAME__\bin\hooks\applypatch-msg.sample",
                        @"C:\__NAME__\obj\hooks\applypatch-msg.sample",
                        @"C:\__NAME__\debug\hooks\applypatch-msg.sample",
                        @"C:\__NAME__\release\hooks\applypatch-msg.sample",
                        @"C:\__NAME__\hooks\applypatch-msg.cache",
                        @"C:\__NAME__\hooks\applypatch-msg.mst",
                        @"C:\__NAME__\hooks\.gitignore",
                        @"C:\__NAME__\hooks\applypatch-msg.idx",
                        @"C:\__NAME__\hooks\applypatch-msg.pack",
                        @"C:\__NAME__\hooks\applypatch-msg.user",
                        @"C:\__NAME__\hooks\applypatch-msg.resharper",
                        @"C:\__NAME__\hooks\applypatch-msg.suo",
                    };
            };
    } ;

    [Subject(typeof(FileExclusionSpecification))]
    public class when_the_file_exclusion_specification_is_given_a_list_of_items_to_exclude : specification_for_file_exclusion_specification
    {
        static FileExclusionSpecification subject;
        static IEnumerable<string> result;

        Establish context = () =>
            {
                subject = new FileExclusionSpecification();
            };

        Because of = () => result = subject.SatisfyingElementsFrom(file_list.AsQueryable());

        It should_return_no_files = () => result.Count().ShouldEqual(0);
    }
}